#!/bin/bash

# 1. Clean up old files
rm -f rom.mem ../rtl/rom.mem

# 2. Run the assembler
python3 assembler.py asm_functions.asm rom.mem

# 3. Strip any Windows line endings generated by the assembler
sed -i 's/\r$//' rom.mem

# 4. Move the file to the RTL directory
if [ -f "rom.mem" ]; then
    cp -f ./rom.mem ../rtl/rom.mem
    echo "INFO: rom.mem copied to RTL successfully."
else
    echo "ERROR: rom.mem was not generated!"
    exit 1
fi

# 5. Run the hardware simulation
cd ..
make clean
make -j $(nproc) main_controller_app TEST=main_controller_app STOP_PC=1 INSTR_TRACE=1 EXTRA_ARGS="-Wno-UNOPTTHREADS"

# 6. Return to software directory
cd sw